name: 'Pull Request Terraform Plan'
on:
  pull_request:
    branches: 
      - master

jobs:
  terraform-plan:
    name: "tplan"
    runs-on: ubuntu-latest
    steps:    
    - name: try echo
      run: echo "hello world pull"
